# Generated by Django 6.1.1 on 2026-09-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_household_invite_code_householdmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('member', 'member')], default='member', max_length=10),
        ),
    ]
